services:
  youtrack:
    image: jetbrains/youtrack:${YOUTRACK_VERSION:-2025.2.93511}
    container_name: youtrack
    user: "13001:13001"
    env_file:
      - stack.env
    volumes:
      - ${YOUTRACK_DATA:-youtrack_data}:/opt/youtrack/data
      - ${YOUTRACK_CONF:-youtrack_conf}:/opt/youtrack/conf
      - ${YOUTRACK_LOGS:-youtrack_logs}:/opt/youtrack/logs
      - ${YOUTRACK_BACKUPS:-youtrack_backups}:/opt/youtrack/backups
    restart: unless-stopped
    ports:
      - "${YOUTRACK_PORT:-8080}:8080"
    networks:
      - youtrack-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  s3fs:
    build:
      context: ./s3fs
      dockerfile: Dockerfile
    env_file:
      - stack.env
    depends_on:
      youtrack:
        condition: service_healthy
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    environment:
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_S3_ACCESS_KEY_ID: "${AWS_S3_ACCESS_KEY_ID}"
      AWS_S3_SECRET_ACCESS_KEY: "${AWS_S3_SECRET_ACCESS_KEY}"
      AWS_S3_URL: "${AWS_S3_URL:-https://s3.us-east-1.amazonaws.com}"
      S3FS_ARGS: "${S3FS_ARGS:--o allow_other -o use_cache=/tmp/cache -o max_stat_cache_size=100000 -o stat_cache_expire=900}"
    volumes:
      - s3fs_bucket:/opt/s3fs/bucket:shared
      - ${YOUTRACK_BACKUPS:-youtrack_backups}:/data/youtrack_backups:ro
      - s3fs_cache:/tmp/cache
    restart: unless-stopped
    networks:
      - youtrack-network
    healthcheck:
      test: ["CMD", "mountpoint", "-q", "/opt/s3fs/bucket"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  youtrack_data:
  youtrack_conf:
  youtrack_logs:
  youtrack_backups:
  s3fs_cache:
  s3fs_bucket:

networks:
  youtrack-network:
    driver: bridge